/** Semantic runtime references to CSS custom properties from styles/tokens.css. */
export const uiColors = {
  appBg: "var(--color-app-bg)",
  sidebarBg: "var(--color-sidebar-bg)",
  surface1: "var(--color-surface-1)",
  surface2: "var(--color-surface-2)",
  surfaceHover: "var(--color-surface-hover)",
  border: "var(--color-border)",
  textPrimary: "var(--color-text-primary)",
  textTertiary: "var(--color-text-tertiary)",
  primary: "var(--color-primary)",
  primaryText: "var(--color-primary-text)",
  primarySubtle: "var(--color-primary-subtle)",
  warningSubtle: "var(--color-warning-subtle)",
  successSubtle: "var(--color-success-subtle)",
  dangerSubtle: "var(--color-danger-subtle)",
  progressTrack: "var(--color-progress-track)",
  borderStrong: "var(--color-border-strong)",
  textSecondary: "var(--color-text-secondary)",
  textDisabled: "var(--color-disabled-text)",
  success: "var(--color-success)",
  warning: "var(--color-warning)",
  danger: "var(--color-danger)",
  violet: "var(--color-accent)",
  categorySky: "var(--color-category-sky)",
  categoryTeal: "var(--color-category-teal)",
  categorySand: "var(--color-category-sand)",
  categoryRose: "var(--color-category-rose)",
  categoryUnlisted: "var(--color-category-unlisted)",
} as const;

export const uiShadows = {
  floating: "var(--shadow-floating)",
} as const;

export const uiLayers = {
  negative: "var(--layer-negative)",
  base: "var(--layer-base)",
  raised: "var(--layer-raised)",
  local: "var(--layer-local)",
  menuLocal: "var(--layer-menu-local)",
  sticky: "var(--layer-sticky)",
  context: "var(--layer-context)",
  detailBackdrop: "var(--layer-detail-backdrop)",
  detail: "var(--layer-detail)",
  detailDrawer: "var(--layer-detail-drawer)",
  pinnedPanel: "var(--layer-pinned-panel)",
  appOverlay: "var(--layer-app-overlay)",
  popover: "var(--layer-popover)",
  drawer: "var(--layer-drawer)",
  overlay: "var(--layer-overlay)",
  modal: "var(--layer-modal)",
  toast: "var(--layer-toast)",
  ambient: "var(--layer-ambient)",
  floating: "var(--layer-floating)",
  featurePopup: "var(--layer-feature-popup)",
  goalToast: "var(--layer-goal-toast)",
  system: "var(--layer-system)",
  nestedPopover: "var(--layer-nested-popover)",
  systemOverlay: "var(--layer-system-overlay)",
} as const;
