-- B06 dual-write bridge. Relational bridge records are the commit source;
-- rootine_workspace_snapshots remains a materialized legacy/recovery view.

create table if not exists public.rootine_sync_account_flags (
  user_id uuid primary key references auth.users(id) on delete cascade,
  dual_write_enabled boolean not null default true,
  shadow_read_enabled boolean not null default true,
  observe_reconciliation boolean not null default true,
  reason text check (reason is null or char_length(reason) <= 500),
  updated_at timestamptz not null default timezone('utc', now())
);

-- B03 calls this compatibility seam rootine_sync_records. Keep the bridge on
-- that same table so mobile-sync pull/push and snapshot writes share state.
create table if not exists public.rootine_sync_records (
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_key text check (storage_key is null or char_length(storage_key) between 1 and 180),
  entity text not null check (char_length(entity) between 1 and 80),
  entity_id text not null check (char_length(entity_id) between 1 and 180),
  payload jsonb not null,
  content_hash text check (content_hash is null or char_length(content_hash) between 1 and 160),
  revision bigint not null check (revision >= 0),
  last_operation_id text,
  last_client_source text not null default 'legacy'
    check (last_client_source in ('web', 'ios', 'legacy', 'system')),
  deleted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, entity, entity_id),
  unique (user_id, storage_key)
);

create table if not exists public.rootine_sync_operations (
  id text primary key default gen_random_uuid()::text,
  user_id uuid not null references auth.users(id) on delete cascade,
  operation_id text not null check (char_length(operation_id) between 1 and 180),
  device_id text,
  command_type text not null default 'workspace_snapshot',
  entity text not null,
  entity_id text not null,
  storage_key text,
  kind text not null default 'upsert' check (kind in ('upsert', 'delete')),
  base_revision bigint not null default 0 check (base_revision >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'applied', 'already_applied', 'conflict', 'invalid', 'disabled')),
  payload jsonb not null default '{}'::jsonb,
  content_hash text not null default '',
  revision bigint not null default 0,
  change_cursor bigint,
  client_source text not null default 'legacy'
    check (client_source in ('web', 'ios', 'legacy', 'system')),
  correlation_id text,
  materialized boolean not null default false,
  reconciliation_id text,
  result jsonb not null default '{}'::jsonb,
  error_code text,
  error_message text,
  applied_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  deleted_at timestamptz,
  unique (user_id, operation_id),
  unique (user_id, id)
);

create table if not exists public.rootine_sync_changes (
  change_cursor bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_key text,
  entity text not null,
  entity_id text not null,
  operation text not null check (operation in ('upsert', 'delete')),
  payload jsonb not null default '{}'::jsonb,
  operation_id text,
  client_source text default 'legacy'
    check (client_source is null or client_source in ('web', 'ios', 'legacy', 'system')),
  revision bigint not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  deleted_at timestamptz
);

create table if not exists public.rootine_workspace_revisions (
  id text primary key default gen_random_uuid()::text,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_key text not null,
  revision bigint not null,
  operation_id text,
  client_source text not null default 'legacy',
  payload jsonb not null default '{}'::jsonb,
  manifest jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, storage_key, revision),
  unique (user_id, id)
);

create table if not exists public.rootine_sync_reconciliation_log (
  id text primary key default gen_random_uuid()::text,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_key text not null,
  correlation_id text not null check (char_length(correlation_id) between 1 and 180),
  domain text not null check (char_length(domain) between 1 and 80),
  entity text not null check (char_length(entity) between 1 and 80),
  entity_id text not null check (char_length(entity_id) between 1 and 180),
  revision bigint not null check (revision > 0),
  client_source text not null check (client_source in ('web', 'ios', 'legacy', 'system')),
  legacy_hash text,
  relational_hash text,
  details jsonb not null default '{}'::jsonb,
  diff_metadata jsonb not null default '{}'::jsonb,
  status text not null default 'different'
    check (status in ('matched', 'migrated', 'different', 'quarantined', 'missing_relational', 'missing_legacy', 'error')),
  created_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz,
  resolved_by text
);

-- B02/B03 own these shared tables when their migrations are present. Add only
-- the bridge metadata that is not part of their base contract so this ticket
-- remains safe to apply both on the current main and after those migrations.
alter table public.rootine_sync_records
  add column if not exists storage_key text,
  add column if not exists content_hash text,
  add column if not exists last_operation_id text,
  add column if not exists last_client_source text default 'legacy';
alter table public.rootine_sync_operations
  add column if not exists id text default gen_random_uuid()::text,
  add column if not exists command_type text default 'workspace_snapshot',
  add column if not exists storage_key text,
  add column if not exists content_hash text default '',
  add column if not exists command_hash text default '',
  add column if not exists change_cursor bigint,
  add column if not exists client_source text default 'legacy',
  add column if not exists correlation_id text,
  add column if not exists materialized boolean default false,
  add column if not exists reconciliation_id text,
  add column if not exists result jsonb default '{}'::jsonb,
  add column if not exists error_code text,
  add column if not exists error_message text,
  add column if not exists updated_at timestamptz default timezone('utc', now()),
  add column if not exists deleted_at timestamptz;
alter table public.rootine_sync_changes
  add column if not exists storage_key text,
  add column if not exists operation_id text,
  add column if not exists client_source text default 'legacy',
  add column if not exists updated_at timestamptz default timezone('utc', now()),
  add column if not exists deleted_at timestamptz;
alter table public.rootine_workspace_revisions
  add column if not exists operation_id text,
  add column if not exists client_source text default 'legacy';
alter table public.rootine_sync_reconciliation_log
  add column if not exists correlation_id text,
  add column if not exists domain text,
  add column if not exists revision bigint,
  add column if not exists client_source text,
  add column if not exists diff_metadata jsonb default '{}'::jsonb;

-- Existing B02/B03 operation ledgers do not include the account kill-switch
-- result. Extend their status check without weakening any other invariant.
alter table public.rootine_sync_operations
  drop constraint if exists rootine_sync_operations_status_check;
alter table public.rootine_sync_operations
  add constraint rootine_sync_operations_status_check
  check (status in ('pending', 'applied', 'already_applied', 'conflict', 'invalid', 'disabled'));

create index if not exists rootine_sync_records_storage_updated_idx
  on public.rootine_sync_records(user_id, storage_key, updated_at desc);
create index if not exists rootine_sync_operations_user_created_idx
  on public.rootine_sync_operations(user_id, created_at desc);
create index if not exists rootine_sync_changes_user_cursor_idx
  on public.rootine_sync_changes(user_id, change_cursor);
create index if not exists rootine_sync_reconciliation_user_created_idx
  on public.rootine_sync_reconciliation_log(user_id, created_at desc);
create index if not exists rootine_sync_reconciliation_domain_idx
  on public.rootine_sync_reconciliation_log(user_id, domain, status);

alter table public.rootine_sync_account_flags enable row level security;
alter table public.rootine_sync_records enable row level security;
alter table public.rootine_sync_operations enable row level security;
alter table public.rootine_sync_changes enable row level security;
alter table public.rootine_workspace_revisions enable row level security;
alter table public.rootine_sync_reconciliation_log enable row level security;

drop policy if exists "Users can read their own sync flags" on public.rootine_sync_account_flags;
create policy "Users can read their own sync flags" on public.rootine_sync_account_flags
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can read their own sync records" on public.rootine_sync_records;
create policy "Users can read their own sync records" on public.rootine_sync_records
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can read their own sync operations" on public.rootine_sync_operations;
create policy "Users can read their own sync operations" on public.rootine_sync_operations
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can read their own sync changes" on public.rootine_sync_changes;
create policy "Users can read their own sync changes" on public.rootine_sync_changes
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can read their own workspace revisions" on public.rootine_workspace_revisions;
create policy "Users can read their own workspace revisions" on public.rootine_workspace_revisions
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can read their own reconciliation log" on public.rootine_sync_reconciliation_log;
create policy "Users can read their own reconciliation log" on public.rootine_sync_reconciliation_log
  for select to authenticated using ((select auth.uid()) = user_id);

-- Authenticated clients receive no table DML; only the functions below can
-- commit bridge data or append reconciliation metadata.
revoke all on table public.rootine_sync_account_flags from anon, authenticated;
revoke all on table public.rootine_sync_records from anon, authenticated;
revoke all on table public.rootine_sync_operations from anon, authenticated;
revoke all on table public.rootine_sync_changes from anon, authenticated;
revoke all on table public.rootine_workspace_revisions from anon, authenticated;
revoke all on table public.rootine_sync_reconciliation_log from anon, authenticated;
grant select on table public.rootine_sync_records to authenticated;
grant select on table public.rootine_sync_operations to authenticated;
grant select on table public.rootine_sync_changes to authenticated;
grant select on table public.rootine_workspace_revisions to authenticated;
grant select on table public.rootine_sync_reconciliation_log to authenticated;

create or replace function public.rootine_bridge_domain(p_storage_key text)
returns text language sql immutable as $$
  select case
    when p_storage_key ilike '%task%' then 'tasks'
    when p_storage_key ilike '%habit%' then 'habits'
    when p_storage_key ilike '%note%' then 'notes'
    when p_storage_key ilike '%nutrition%' then 'nutrition'
    when p_storage_key ilike '%sport%' then 'sport'
    when p_storage_key ilike '%goal%' then 'goals'
    when p_storage_key ilike '%work%' then 'work'
    when p_storage_key ilike '%travel%' then 'travel'
    when p_storage_key ilike '%health%' then 'health'
    when p_storage_key ilike '%affair%' then 'affairs'
    else 'workspace'
  end;
$$;

create or replace function public.rootine_materialize_legacy_snapshot(
  p_user_id uuid, p_storage_key text, p_payload jsonb, p_content_hash text,
  p_revision bigint
)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if p_revision is null or p_revision < 1 then
    raise exception 'Materialized revision must be positive.' using errcode = '22023';
  end if;
  insert into public.rootine_workspace_snapshots as snapshots
    (user_id, storage_key, payload, content_hash, revision, updated_at)
  values (p_user_id, p_storage_key, p_payload, p_content_hash, p_revision, timezone('utc', now()))
  on conflict (user_id, storage_key) do update set
    payload = excluded.payload,
    content_hash = excluded.content_hash,
    revision = excluded.revision,
    updated_at = timezone('utc', now());
  return true;
end;
$$;
revoke all on function public.rootine_materialize_legacy_snapshot(uuid, text, jsonb, text, bigint) from public;

create or replace function public.rootine_dual_write_workspace_snapshot(
  p_storage_key text,
  p_payload jsonb,
  p_content_hash text,
  p_expected_revision bigint,
  p_operation_id text default null,
  p_client_source text default 'legacy',
  p_correlation_id text default null,
  p_cursor bigint default 0
)
returns table (
  applied boolean, operation_status text, operation_id text, storage_key text,
  payload jsonb, content_hash text, revision bigint, change_cursor bigint,
  updated_at timestamptz, client_source text, materialized boolean,
  reconciliation_id text, error_message text
)
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  op_id text := coalesce(nullif(p_operation_id, ''), 'legacy:' || md5(coalesce(p_storage_key, '') || ':' || clock_timestamp()::text));
  correlation text := coalesce(nullif(p_correlation_id, ''), op_id);
  source text := coalesce(nullif(p_client_source, ''), 'legacy');
  bridge_row public.rootine_sync_records%rowtype;
  old_op public.rootine_sync_operations%rowtype;
  old_snapshot public.rootine_workspace_snapshots%rowtype;
  enabled boolean := true;
  materialized_ok boolean := false;
  new_revision bigint;
  new_cursor bigint;
  log_id text;
  after_payload jsonb;
begin
  if uid is null then raise exception 'Authentication is required.' using errcode = '42501'; end if;
  if p_storage_key is null or char_length(p_storage_key) not between 1 and 180 then
    raise exception 'Invalid storage key.' using errcode = '22023';
  end if;
  if p_payload is null or p_content_hash is null or char_length(p_content_hash) not between 1 and 160 then
    raise exception 'Invalid bridge payload.' using errcode = '22023';
  end if;
  if jsonb_typeof(p_payload) <> 'object' then
    raise exception 'Bridge payload must be a JSON object.' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'Expected revision cannot be negative.' using errcode = '22023';
  end if;
  if char_length(op_id) > 180 or source not in ('web', 'ios', 'legacy', 'system') then
    raise exception 'Invalid bridge metadata.' using errcode = '22023';
  end if;

  insert into public.rootine_sync_account_flags(user_id) values (uid) on conflict do nothing;
  select dual_write_enabled into enabled from public.rootine_sync_account_flags where user_id = uid;

  -- Serialize first-writer races for a workspace that has no bridge row yet;
  -- this also makes concurrent retries of the same operation deterministic.
  perform pg_advisory_xact_lock(hashtextextended(uid::text || ':' || p_storage_key, 0));

  select * into old_op from public.rootine_sync_operations
    where user_id = uid and operation_id = op_id for update;
  if found then
    if old_op.storage_key <> p_storage_key or old_op.content_hash <> p_content_hash then
      return query select false, 'invalid', old_op.operation_id, old_op.storage_key,
        old_op.payload, old_op.content_hash, old_op.revision, old_op.change_cursor,
        coalesce(old_op.applied_at, old_op.created_at), old_op.client_source,
        old_op.materialized, old_op.reconciliation_id,
        'Operation ID has already been used for a different payload.';
      return;
    end if;
    return query select old_op.status in ('applied', 'already_applied'),
      case when old_op.status = 'applied' then 'already_applied' else old_op.status end,
      old_op.operation_id, old_op.storage_key, old_op.payload, old_op.content_hash,
      old_op.revision, old_op.change_cursor, coalesce(old_op.applied_at, old_op.created_at),
      old_op.client_source, old_op.materialized, old_op.reconciliation_id, old_op.error_message;
    return;
  end if;

  select * into bridge_row from public.rootine_sync_records
    where user_id = uid and storage_key = p_storage_key for update;
  if not found then
    select * into old_snapshot from public.rootine_workspace_snapshots
      where user_id = uid and storage_key = p_storage_key;
    if found then
      insert into public.rootine_sync_records
        (user_id, storage_key, entity, entity_id, payload, content_hash, revision,
         last_client_source, created_at, updated_at)
      values (uid, p_storage_key, public.rootine_bridge_domain(p_storage_key), p_storage_key,
        old_snapshot.payload, old_snapshot.content_hash, old_snapshot.revision,
        'legacy', old_snapshot.created_at, old_snapshot.updated_at)
  on conflict (user_id, entity, entity_id) do nothing;
      select * into bridge_row from public.rootine_sync_records
        where user_id = uid and storage_key = p_storage_key for update;
    end if;
  end if;

  if not enabled then
    insert into public.rootine_sync_operations
      (user_id, operation_id, entity, entity_id, storage_key, kind, base_revision,
       status, payload, content_hash, revision, client_source, correlation_id,
       error_message, result, updated_at)
    values (uid, op_id, public.rootine_bridge_domain(p_storage_key), p_storage_key,
      p_storage_key, 'upsert', p_expected_revision, 'disabled',
      coalesce(bridge_row.payload, '{}'::jsonb), coalesce(bridge_row.content_hash, ''),
      greatest(coalesce(bridge_row.revision, 0), 1), source, correlation,
      'Dual-write is disabled for this account.',
      jsonb_build_object('status', 'disabled', 'operation_id', op_id), timezone('utc', now()));
    return query select false, 'disabled', op_id, p_storage_key,
      coalesce(bridge_row.payload, '{}'::jsonb), coalesce(bridge_row.content_hash, ''),
      coalesce(bridge_row.revision, 0), null::bigint, timezone('utc', now()), source,
      false, null::text, 'Dual-write is disabled for this account.';
    return;
  end if;

  if bridge_row.revision is not null and bridge_row.revision <> p_expected_revision then
    insert into public.rootine_sync_operations
      (user_id, operation_id, entity, entity_id, storage_key, kind, base_revision,
       status, payload, content_hash, revision, client_source, correlation_id,
       error_message, result, updated_at)
    values (uid, op_id, public.rootine_bridge_domain(p_storage_key), p_storage_key,
      p_storage_key, 'upsert', p_expected_revision, 'conflict', bridge_row.payload,
      bridge_row.content_hash, greatest(bridge_row.revision, 1), source, correlation,
      'The bridge record revision is newer.',
      jsonb_build_object('status', 'conflict', 'revision', bridge_row.revision), timezone('utc', now()));
    return query select false, 'conflict', op_id, p_storage_key, bridge_row.payload,
      bridge_row.content_hash, bridge_row.revision, null::bigint, bridge_row.updated_at,
      source, false, null::text, 'The bridge record revision is newer.';
    return;
  end if;

  new_revision := coalesce(bridge_row.revision, 0) + 1;
  insert into public.rootine_sync_records
    (user_id, storage_key, entity, entity_id, payload, content_hash, revision,
     last_operation_id, last_client_source, deleted_at, created_at, updated_at)
  values (uid, p_storage_key, public.rootine_bridge_domain(p_storage_key), p_storage_key,
    p_payload, p_content_hash, new_revision, op_id, source,
    case when p_payload ? 'deletedAt' and p_payload->>'deletedAt' is not null
      then (p_payload->>'deletedAt')::timestamptz else null end,
    coalesce(bridge_row.created_at, timezone('utc', now())), timezone('utc', now()))
  on conflict (user_id, entity, entity_id) do update set
    payload = excluded.payload, content_hash = excluded.content_hash,
    revision = excluded.revision, last_operation_id = excluded.last_operation_id,
    last_client_source = excluded.last_client_source, deleted_at = excluded.deleted_at,
    updated_at = excluded.updated_at;

  insert into public.rootine_sync_changes
    (user_id, storage_key, entity, entity_id, operation, payload,
     revision, operation_id, client_source, created_at, updated_at, deleted_at)
  values (uid, p_storage_key, public.rootine_bridge_domain(p_storage_key), p_storage_key,
    case when p_payload ? 'deletedAt' and p_payload->>'deletedAt' is not null then 'delete' else 'upsert' end,
    p_payload, new_revision, op_id, source, timezone('utc', now()), timezone('utc', now()),
    case when p_payload ? 'deletedAt' and p_payload->>'deletedAt' is not null
      then (p_payload->>'deletedAt')::timestamptz else null end)
  returning change_cursor into new_cursor;
  insert into public.rootine_workspace_revisions
    (user_id, storage_key, revision, operation_id, client_source, payload, manifest)
  values (uid, p_storage_key, new_revision, op_id, source,
    p_payload, jsonb_build_object('content_hash', p_content_hash, 'cursor', new_cursor))
  on conflict do nothing;
  insert into public.rootine_sync_operations
    (user_id, operation_id, entity, entity_id, storage_key, kind, base_revision,
     status, payload, content_hash, revision, change_cursor, client_source,
     correlation_id, result, materialized, applied_at, updated_at)
  values (uid, op_id, public.rootine_bridge_domain(p_storage_key), p_storage_key, p_storage_key,
    case when p_payload ? 'deletedAt' and p_payload->>'deletedAt' is not null then 'delete' else 'upsert' end,
    p_expected_revision, 'applied', p_payload, p_content_hash, new_revision, new_cursor,
    source, correlation, jsonb_build_object('status', 'applied', 'cursor', new_cursor,
      'revision', new_revision, 'base_cursor', p_cursor), false, timezone('utc', now()), timezone('utc', now()));

  -- The exception block is a subtransaction: relational changes above remain
  -- auditable while a failed legacy materializer is queued for recovery.
  begin
    perform public.rootine_materialize_legacy_snapshot(uid, p_storage_key, p_payload, p_content_hash, new_revision);
    materialized_ok := true;
    select payload into after_payload from public.rootine_workspace_snapshots
      where user_id = uid and storage_key = p_storage_key;
    if after_payload is distinct from p_payload then
      begin
        insert into public.rootine_sync_reconciliation_log
          (user_id, storage_key, correlation_id, domain, entity, entity_id, revision,
           client_source, details, diff_metadata, status)
        values (uid, p_storage_key, correlation, public.rootine_bridge_domain(p_storage_key), 'workspace', p_storage_key,
          new_revision, source, jsonb_build_object('kind', 'materialized_canonical_diff',
            'changed_paths', jsonb_build_array('$'), 'left_type', jsonb_typeof(p_payload),
            'right_type', jsonb_typeof(after_payload)), jsonb_build_object('kind', 'materialized_canonical_diff',
            'changed_paths', jsonb_build_array('$'), 'left_type', jsonb_typeof(p_payload),
            'right_type', jsonb_typeof(after_payload)), 'different') returning id into log_id;
      exception when others then log_id := null;
      end;
    end if;
  exception when others then
    materialized_ok := false;
    begin
      insert into public.rootine_sync_reconciliation_log
        (user_id, storage_key, correlation_id, domain, entity, entity_id, revision,
         client_source, details, diff_metadata, status)
      values (uid, p_storage_key, correlation, public.rootine_bridge_domain(p_storage_key), 'workspace',
        p_storage_key, new_revision, source, jsonb_build_object('kind', 'materializer_failure',
          'error_code', SQLSTATE, 'changed_paths', jsonb_build_array('$')),
        jsonb_build_object('kind', 'materializer_failure', 'error_code', SQLSTATE,
          'changed_paths', jsonb_build_array('$')), 'error') returning id into log_id;
    exception when others then log_id := null;
    end;
  end;
  update public.rootine_sync_operations set materialized = materialized_ok, reconciliation_id = log_id
    where user_id = uid and operation_id = op_id;
  return query select true, 'applied', op_id, p_storage_key, p_payload, p_content_hash,
    new_revision, new_cursor, timezone('utc', now()), source, materialized_ok, log_id,
    case when materialized_ok then null else 'Relational commit succeeded; legacy recovery is required.' end;
end;
$$;

revoke all on function public.rootine_dual_write_workspace_snapshot(text, jsonb, text, bigint, text, text, text, bigint) from public;
grant execute on function public.rootine_dual_write_workspace_snapshot(text, jsonb, text, bigint, text, text, text, bigint) to authenticated;

-- Keep the historical RPC name for both old and B06 clients during rollout.
create or replace function public.rootine_apply_workspace_snapshot(
  p_storage_key text, p_payload jsonb, p_content_hash text, p_expected_revision bigint,
  p_operation_id text, p_client_source text, p_correlation_id text, p_cursor bigint
)
returns table (
  applied boolean, operation_status text, operation_id text, storage_key text, payload jsonb,
  content_hash text, revision bigint, change_cursor bigint, updated_at timestamptz,
  client_source text, materialized boolean, reconciliation_id text, error_message text
)
language sql security definer set search_path = public as $$
  select * from public.rootine_dual_write_workspace_snapshot(
    p_storage_key, p_payload, p_content_hash, p_expected_revision,
    p_operation_id, p_client_source, p_correlation_id, p_cursor);
$$;
revoke all on function public.rootine_apply_workspace_snapshot(text, jsonb, text, bigint, text, text, text, bigint) from public;
grant execute on function public.rootine_apply_workspace_snapshot(text, jsonb, text, bigint, text, text, text, bigint) to authenticated;

create or replace function public.rootine_apply_workspace_snapshot(
  p_storage_key text, p_payload jsonb, p_content_hash text, p_expected_revision bigint
)
returns table (applied boolean, storage_key text, payload jsonb, content_hash text, revision bigint, updated_at timestamptz)
language sql security definer set search_path = public as $$
  select applied, storage_key, payload, content_hash, revision, updated_at
  from public.rootine_dual_write_workspace_snapshot(
    p_storage_key, p_payload, p_content_hash, p_expected_revision, null, 'legacy', null, 0);
$$;
revoke all on function public.rootine_apply_workspace_snapshot(text, jsonb, text, bigint) from public;
grant execute on function public.rootine_apply_workspace_snapshot(text, jsonb, text, bigint) to authenticated;

create or replace function public.rootine_record_sync_reconciliation(
  p_domain text, p_entity text, p_entity_id text, p_revision bigint,
  p_client_source text, p_correlation_id text, p_diff_metadata jsonb
)
returns text language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); result_id text; safe_diff jsonb;
begin
  if uid is null then raise exception 'Authentication is required.' using errcode = '42501'; end if;
  if p_domain is null or p_entity is null or p_entity_id is null or p_revision is null or p_revision < 1
    or p_client_source not in ('web', 'ios', 'legacy', 'system') or p_correlation_id is null
    or p_diff_metadata is null then
    raise exception 'Invalid reconciliation metadata.' using errcode = '22023';
  end if;
  safe_diff := jsonb_build_object(
    'changed_paths', coalesce(p_diff_metadata->'changedPaths', p_diff_metadata->'changed_paths', '[]'::jsonb),
    'left_hash', coalesce(p_diff_metadata->'leftHash', p_diff_metadata->'left_hash'),
    'right_hash', coalesce(p_diff_metadata->'rightHash', p_diff_metadata->'right_hash'),
    'left_type', coalesce(p_diff_metadata->'leftType', p_diff_metadata->'left_type'),
    'right_type', coalesce(p_diff_metadata->'rightType', p_diff_metadata->'right_type'),
    'truncated', coalesce(p_diff_metadata->'truncated', false));
  insert into public.rootine_sync_reconciliation_log
    (user_id, storage_key, correlation_id, domain, entity, entity_id, revision,
     client_source, details, diff_metadata, status)
  values (uid, left(p_entity_id, 180), left(p_correlation_id, 180), left(p_domain, 80),
    left(p_entity, 80), left(p_entity_id, 180), p_revision, p_client_source,
    safe_diff, safe_diff, 'different') returning id into result_id;
  return result_id;
end;
$$;
revoke all on function public.rootine_record_sync_reconciliation(text, text, text, bigint, text, text, jsonb) from public;
grant execute on function public.rootine_record_sync_reconciliation(text, text, text, bigint, text, text, jsonb) to authenticated;

create or replace function public.rootine_get_dual_write_flags()
returns table (dual_write_enabled boolean, shadow_read_enabled boolean, observe_reconciliation boolean, reason text)
language sql security definer set search_path = public as $$
  select dual_write_enabled, shadow_read_enabled, observe_reconciliation, reason
  from public.rootine_sync_account_flags where user_id = auth.uid()
  union all select true, true, true, null::text where auth.uid() is not null
    and not exists (select 1 from public.rootine_sync_account_flags where user_id = auth.uid());
$$;
revoke all on function public.rootine_get_dual_write_flags() from public;
grant execute on function public.rootine_get_dual_write_flags() to authenticated;

create or replace function public.rootine_set_dual_write_enabled(p_enabled boolean, p_reason text default null)
returns public.rootine_sync_account_flags
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); result public.rootine_sync_account_flags;
begin
  if uid is null then raise exception 'Authentication is required.' using errcode = '42501'; end if;
  insert into public.rootine_sync_account_flags(user_id, dual_write_enabled, reason, updated_at)
  values (uid, coalesce(p_enabled, true), left(p_reason, 500), timezone('utc', now()))
  on conflict (user_id) do update set dual_write_enabled = excluded.dual_write_enabled,
    reason = excluded.reason, updated_at = excluded.updated_at returning * into result;
  return result;
end;
$$;
revoke all on function public.rootine_set_dual_write_enabled(boolean, text) from public;
grant execute on function public.rootine_set_dual_write_enabled(boolean, text) to authenticated;

create or replace function public.rootine_sync_reconciliation_summary()
returns table (domain text, status text, difference_count bigint, latest_revision bigint, latest_created_at timestamptz)
language sql security definer set search_path = public as $$
  select domain, status, count(*)::bigint, max(revision), max(created_at)
  from public.rootine_sync_reconciliation_log where user_id = auth.uid()
  group by domain, status order by domain, status;
$$;
revoke all on function public.rootine_sync_reconciliation_summary() from public;
grant execute on function public.rootine_sync_reconciliation_summary() to authenticated;

-- Legacy remains readable for hydration/export but cannot be written directly.
revoke insert, update, delete on table public.rootine_workspace_snapshots from authenticated;
